var arrObj = [
  { 'company':'apple',
    'serise':'iphone',
    'site':'http://apple.com',
    'img':'img_01.jpg',
    'content' : '2020 하반기 최신 아이폰 출시'},
  { 'company':'samsung',
    'serise' : 'galaxy21',
    'site' : 'https://samsung.com',
    'img' : 'img_02.jpg',
    'content' : '갤럭시 21 부품 유출'},
  { 'company':'LG',
    'serise' :'wing',
    'site' : 'https://lg.com',
    'img' : 'img_03.jpg',
    'content' : '가로본능 이즈 백'},
  { 'company':'xiaomi',
    'serise':'redmi',
    'site':'https://mi.com',
    'img':'img_04.jpg',
    'content' : '밀리지 않는 성능'},
];